#Project Information
site_name: HCL Digital Experience Help Center
site_description: >-
  A next-gen documentation site for HCL Digital Experience.
use_directory_urls: false

# Theme Configuration
theme:
  name: material
  logo: assets/dx_logo.png
  language: en
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.share
    - search.suggest
  custom_dir: theme_overrides/
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png

  # Static files
  static_templates:
    - 404.html

# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

# Copyright
copyright: Copyright &copy; 2022, HCL Technologies Limited

extra:
  analytics: 
    provider: custom
    property: UA-169645537-2
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HCL-TECH-SOFTWARE
  version:
    provider: mike
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
  prodname: HCL Software

# Repository
repo_url: https://github.com/HCL-TECH-SOFTWARE/digital-experience
repo_name: HCL-TECH-SOFTWARE/digital-experience
edit_uri: edit/main/docs

# Customization
extra_css:
  - stylesheets/style.css
  # - sofy.css

plugins:
  - awesome-pages
  - search
 # - git-revision-date-localized:
  #    type: date
  #- macros
